# Generated by Django 4.2.1 on 2023-06-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('MATERIAL', 'Material')], max_length=20)),
                ('title', models.CharField(max_length=64)),
                ('instruction', models.TextField()),
                ('score', models.FloatField()),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('creator', models.ManyToManyField(related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_section', models.CharField(blank=True, max_length=64)),
                ('course_room', models.CharField(blank=True, max_length=64)),
                ('course_banner', models.ImageField(blank=True, upload_to='')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruct_course', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_section', to='educ_web.post')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_section', to='educ_web.task')),
            ],
        ),
    ]
