# Generated by Django 4.2.1 on 2023-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0002_task_post_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_banner',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_section',
            new_name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='classcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
