# Generated by Django 4.2.1 on 2023-06-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0004_alter_course_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_section', to='educ_web.task'),
        ),
    ]
