# Generated by Django 4.2.1 on 2023-06-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0005_alter_course_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
