# Generated by Django 4.2.1 on 2023-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0008_remove_post_creator_alter_task_score_post_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
