# Generated by Django 4.2.1 on 2023-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0009_remove_post_date_post_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
