# Generated by Django 4.2.1 on 2023-06-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0011_alter_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='course_code',
        ),
    ]
