# Generated by Django 4.2.1 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0012_rename_subject_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
