# Generated by Django 4.2.1 on 2023-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0014_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, upload_to='course/'),
        ),
    ]
