# Generated by Django 4.2.1 on 2023-06-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0015_alter_course_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
