# Generated by Django 4.2.1 on 2023-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0016_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_time',
        ),
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
