# Generated by Django 4.2.1 on 2023-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0017_remove_task_due_date_remove_task_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
