# Generated by Django 4.2.1 on 2023-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0018_task_due_date_time_alter_task_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
