# Generated by Django 4.2.1 on 2023-06-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0022_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
