# Generated by Django 4.2.1 on 2024-02-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0025_remove_user_admin_remove_user_staff_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
