# Generated by Django 4.2.1 on 2024-02-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0026_user_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='attached_file',
        ),
        migrations.AddField(
            model_name='submission',
            name='attached_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
