# Generated by Django 4.2.1 on 2024-03-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educ_web', '0027_remove_submission_attached_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
